require:
  - rubocop-packaging

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 28

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - faraday-http.gemspec

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 11

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
